### PR TITLE
Add code styling for file naming in components

### PR DESCRIPTION
**Pull request by daemyonc**

### CODE REVIEW

**Review by ShaunWMusic — COMMENTED** [review]
i believe you can use the generator to create what u want, yea? have u tried?

**Comment by daemyonc** [comment]
The generate command you shared about the pod styles created a template file named template.hbs. Ember g component top-nav -p created a folder named top-nav with that template file in it.

**Comment by daemyonc** [comment]
Seems like you might be able do something with blueprints but not really sure I want to go down that rabbit hole

**Comment by ShaunWMusic** [comment]
you could try to remove the `-p` 

Screen Shot 2021-03-01 at 8 04 31 AM

**Comment by daemyonc** [comment]
I think I would rather have everything in it's own folder. I'll be fine with the pods.

**Pull request closed without merging**
